### PR TITLE
Tiny wording fix to README.md

### PR DESCRIPTION
**Pull request by gunnarmorling**

### CODE REVIEW

**Comment by ftomassetti** [comment]
It is an honor to get a PR from you :)

**Comment by gunnarmorling** [comment]
My pleasure, also if it's just such a tiny change.

Great to see some activity in this field, it would indeed be nice if
JavaParser could move to Antlr at some point.

**Comment by matozoid** [comment]
@ftomassetti @gunnarmorling I did a little home hackathon and got it to parse some code already. I ran out of energy now... Should I put it up as a fork somewhere for other to work on?

**Comment by ftomassetti** [comment]
Yes, I think it would be a good idea. I could also mark this version as deprecated and point to yours as the most recent one

**Comment by matozoid** [comment]
@ftomassetti oh, no I mean my JavaParser running on Antlr.

**Comment by ftomassetti** [comment]
I think it would be interesting, yes!
And it could be useful if you wrote down a few lines about what was your process, while your memory is still fresh

**Comment by matozoid** [comment]
Good, I did that here: https://github.com/matozoid/javaparser

**Pull request merged**
